= tinypad: a tiny Notepad/textpad style editor in Java

Well, it all fits in one source file, so you know it isn't going to displace TextPad or NotePad++.
Not to mention Emacs.

Currently offers a single-window text edit function, with undo/redo capability.

== Origins

Bits of this code are adapted from an earlier editor ("EzEditor") used in the GUI chapter of
https://learningtree.com/471[Learning Tree's Introductory Java Course].
My version is quite a bit more fully fleshed out, and significantly modernized.
Very little of the original code remains.

The icons are from 

. https://freeiconshop.com/icon/
. https://findicons.com/
. the _Java Look and Feel Guidelines_ download file _jlfgr.jar_.

As with all free software, use at own risk.

If you want a real, full-functioned window editor (not necessarily written in Java),
check out
https://notepad-plus-plus.org/[NotePad++] (free, open-source, MS-Windows only) or
https://www.textpad.com/[TextPad] (not free; MS-Windows only).
For Unix/Linux, KDE and GNOME both feature their own window editors,
and there are others (web search is your friend).

